/*
 * File: app/store/Followers.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('qrunch.store.Followers', {
  extend: 'Ext.data.Store',

  config: {
    data: [
      {
        name: 'Gianlugi Buffon',
        avatar: 'resources/images/grumpycat.jpg',
        hashtag: 'buffon',
        fans: 123
      },
      {
        name: 'Giorgio Chiellini',
        avatar: 'resources/images/grumpycat.jpg',
        hashtag: 'chiellini',
        fans: 123
      },
      {
        name: 'Leonardo Bonucci',
        avatar: 'resources/images/grumpycat.jpg',
        hashtag: 'bonucci',
        fans: 123
      },
      {
        name: 'Mirko Vucinic',
        avatar: 'resources/images/grumpycat.jpg',
        hashtag: 'vucinic',
        fans: 123
      },
      
    ],
    storeId: 'Followers',
    fields: [
      {
        name: 'name'
      },
      {
        name: 'hashtag'
      },
      {
        name: 'fans'
      },
      {
        name: 'avatar'
      }
    ]
  }
});