/*
 * File: app/view/Interests.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('qrunch.view.Interests', {
  extend: 'Ext.Container',
  alias: 'widget.Interests',

  config: {
    id: 'interests',
    layout: {
      type: 'vbox'
    },
    cls: [
      'bg'
    ],
    scrollable: {
      direction: 'vertical',
      directionLock: true,
      
    },
    items: [
      {
        xtype: 'container',
        docked: 'top',
        height: '40px',
        style: 'margin: 5% 5% 2% 5%; padding: 0;',
        layout: {
          type: 'hbox'
        },
        items: [
          {
            xtype: 'textfield',
            cls: [
              'interest-txt'
            ],
            disabled: true
          },
          {
            xtype: 'button',
            baseCls: 'interest-plus-btn',
            pressedCls: 'interest-plus-btn-pressed'
          }
        ]
      },
      {
        xtype: 'label',
        baseCls: 'left-lbl',
        docked: 'top',
        html: 'Interests'
      },
      {
        xtype: 'list',
        flex: 1,
        cls: [
          'interest-list'
        ],
        itemCls: 'interest-item',
        itemTpl: [
          '{title}',
          '<div class="interest-pop-down">',
          '    <button>src</button>',
          '    <button>del</button>',
          '</div>'
        ],
        selectedCls: 'actived-interest',
        store: 'Interests'
      }
    ]
  }

});