/*
 * File: app/view/ContentSelection.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('qrunch.view.ContentSelection', {
  extend: 'Ext.Container',
  alias: 'widget.ContentSelection',

  config: {
    itemId: 'content-selection',
    layout: {
      type: 'vbox'
    },
    scrollable: false,
    cls: [
      'bg'
    ],
    items: [
      {
        xtype: 'label',
        baseCls: 'centered-lbl',
        docked: 'top',
        html: 'Content Selection'
      },
      {
        xtype: 'container',
        docked: 'top',
        height: '50px',
        layout: {
          type: 'hbox'
        },
        items: [
          {
            xtype: 'textfield',
            baseCls: '',
            cls: [
              'overlay-txt'
            ],
            label: 'Field'
          },
          {
            xtype: 'button',
            baseCls: 'plus-btn',
            pressedCls: 'highlight-pressed'
          }
        ]
      },
      {
        xtype: 'container',
        flex: 1,
        style: 'margin-top: 100px;',
        ui: '',
        scrollable: true,
        items: [
          {
            xtype: 'container',
            baseCls: 'left-content-box',
            height: '150px',
            html: 'whitebox',
            width: '49.5%'
          },
          {
            xtype: 'container',
            baseCls: 'left-content-box',
            height: '150px',
            html: 'whitebox',
            width: '49.5%'
          },
          {
            xtype: 'container',
            baseCls: 'left-content-box',
            height: '150px',
            html: 'whitebox',
            width: '49.5%'
          },
          {
            xtype: 'container',
            baseCls: 'left-content-box',
            height: '150px',
            html: 'whitebox',
            width: '49.5%'
          },
          {
            xtype: 'container',
            baseCls: 'left-content-box',
            height: '150px',
            html: 'whitebox',
            width: '49.5%'
          },
          {
            xtype: 'container',
            baseCls: 'left-content-box',
            height: '150px',
            html: 'whitebox',
            width: '49.5%'
          },
          {
            xtype: 'container',
            baseCls: 'left-content-box',
            height: '150px',
            html: 'whitebox',
            width: '49.5%'
          },
          {
            xtype: 'container',
            baseCls: 'left-content-box',
            height: '150px',
            html: 'whitebox',
            width: '49.5%'
          }
        ]
      }
    ]
  }

});