/*
 * File: app/view/LoginView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('qrunch.view.LoginView', {
  extend: 'Ext.Container',
  alias: 'widget.LoginView',

  config: {
    layout: {
      type: 'card'
    },
    items: [
      {
        xtype: 'formpanel',
        cls: [
          'login-form'
        ],
        styleHtmlContent: true,
        scrollable: false,
        items: [
          {
            xtype: 'image',
            cls: [
              'logo'
            ],
            height: '150px',
            style: 'margin-top: 20%; margin-bottom: 10%;',
            src: 'resources/images/logo.png'
          },
          {
            xtype: 'emailfield',
            id: 'login-view-email',
            style: 'margin-bottom: 4%; margin-left: 10%;',
            width: '80%',
            label: '&nbsp;',
            labelCls: 'email-field-label',
            labelWidth: '45px',
            name: 'name',
            placeHolder: 'Username'
          },
          {
            xtype: 'passwordfield',
            id: 'login-view-password',
            style: 'margin-bottom: 4%; margin-left: 10%;',
            width: '80%',
            label: '&nbsp;',
            labelCls: 'password-field-label',
            labelWidth: '45px',
            name: 'password',
            placeHolder: 'Password'
          },
          {
            xtype: 'button',
            baseCls: 'login-btn',
            id: 'login-button',
            itemId: 'mybutton1',
            style: 'margin-left: 10%;',
            width: '80%',
            pressedCls: 'login-btn-pressed',
            text: 'Sign In'
          },
          {
            xtype: 'button',
            baseCls: 'login-btn',
            id: 'signup-button',
            itemId: 'mybutton1',
            style: 'margin-left: 10%; margin-top: 10px;',
            width: '80%',
            pressedCls: 'login-btn-pressed',
            text: 'Create new profile'
          }
        ]
      }
    ]
  }

});