/*
 * File: app/view/RegistrationView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('qrunch.view.RegistrationView', {
  extend: 'Ext.Container',
  alias: 'widget.registrationview',

  config: {
    layout: {
      type: 'card'
    },
    items: [
      {
        xtype: 'formpanel',
        cls: [
          'login-form'
        ],
        styleHtmlContent: true,
        scrollable: false,
        items: [
          {
            xtype: 'label',
            html: 'REGISTRATION PAGE',
            style: 'color: white; margin-bottom: 10px;'
          },
          {
            xtype: 'textfield',
            id: 'registration-view-username',
            style: 'margin-bottom: 4%; margin-left: 10%;',
            width: '80%',
            label: '&nbsp;',
            labelCls: 'email-field-label',
            labelWidth: '45px',
            name: 'name',
            placeHolder: 'Username'
          },
          {
            xtype: 'emailfield',
            hidden: true,
            id: 'registration-view-email',
            style: 'margin-bottom: 4%; margin-left: 10%;',
            width: '80%',
            label: '&nbsp;',
            labelCls: 'email-field-label',
            labelWidth: '45px',
            name: 'name',
            placeHolder: 'Email'
          },
          {
            xtype: 'passwordfield',
            id: 'registration-view-password',
            style: 'margin-bottom: 4%; margin-left: 10%;',
            width: '80%',
            label: '&nbsp;',
            labelCls: 'password-field-label',
            labelWidth: '45px',
            name: 'password',
            placeHolder: 'Password'
          },
          {
            xtype: 'textfield',
            id: 'registration-view-firstname',
            style: 'margin-bottom: 4%; margin-left: 10%;',
            width: '80%',
            label: '&nbsp;',
            labelCls: 'password-field-label',
            labelWidth: '45px',
            name: 'password',
            placeHolder: 'First Name'
          },
          {
            xtype: 'textfield',
            id: 'registration-view-lastname',
            style: 'margin-bottom: 4%; margin-left: 10%;',
            width: '80%',
            label: '&nbsp;',
            labelCls: 'password-field-label',
            labelWidth: '45px',
            name: 'password',
            placeHolder: 'Last Name'
          },
          {
            xtype: 'button',
            baseCls: 'login-btn',
            id: 'registration-view-signup',
            itemId: 'mybutton1',
            style: 'margin-left: 10%; margin-top: 10px;',
            width: '80%',
            pressedCls: 'login-btn-pressed',
            text: 'Sign Up!'
          }
        ]
      }
    ]
  }

});