/*
 * File: app/view/SliderView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('qrunch.view.SliderView', {
  extend: 'Ext.Container',
  alias: 'widget.SliderView',

  config: {
    hidden: true,
    id: 'slider-view',
    width: '250px',
    layout: {
      type: 'card'
    },
    items: [
      {
        xtype: 'container',
        cls: [
          'bg'
        ],
        id: 'slider-view-content',
        layout: {
          type: 'vbox'
        },
        scrollable: 'vertical',
        items: [
          {
            xtype: 'panel',
            height: '255px',
            html: '<div style="height: 255px; background-repeat: no-repeat; background-size: 100%; background-image: url(resources/images/juve.png);"><div style="position: absolute; bottom: 0; background-color: rgba(0,0,0,0.4); width: 100%; color: white; font-size: 20px; font-weight: bold; padding: 5px 10px; text-align: center;">BASHIR OSMAN</div></div>',
            itemId: 'mypanel15'
          },
          {
            xtype: 'container',
            height: 80,
            width: '100%',
            layout: {
              type: 'hbox'
            },
            items: [
              {
                xtype: 'button',
                baseCls: 'slider-btn',
                cls: 'slider-interest-btn',
                itemId: 'interests',
                width: '50%',
                text: 'interests'
              },
              {
                xtype: 'button',
                baseCls: 'slider-btn',
                cls: 'slider-percentage-btn',
                itemId: 'mybutton9',
                width: '50%',
                text: '45%'
              }
            ]
          },
          {
            xtype: 'container',
            height: 80,
            width: '100%',
            layout: {
              type: 'hbox'
            },
            items: [
              {
                xtype: 'button',
                baseCls: 'slider-btn',
                cls: 'slider-followers-btn',
                itemId: 'followers',
                width: '50%',
                text: '<div class="follow-label">FOLLOWERS</div><div class="follow-number">450</div>'
              },
              {
                xtype: 'button',
                baseCls: 'slider-btn',
                cls: 'slider-following-btn',
                itemId: 'following',
                width: '50%',
                text: '<div class="follow-label">FOLLOWING</div><div class="follow-number">900</div>'
              }
            ]
          }
        ]
      }
    ],
    listeners: [
      {
        fn: 'showPersonalStream',
        element: 'element',
        event: 'tap',
        delegate: '#mypanel15'
      },
      {
        fn: 'showFriendProfile',
        event: 'tap',
        delegate: '#mybutton9'
      },
      {
        fn: 'onFollowersTap',
        event: 'tap',
        delegate: '#followers'
      },
      {
        fn: 'onFollowingTap',
        event: 'tap',
        delegate: '#following'
      }
    ]
  },

  showPersonalStream: function(panel) {
    var controller = qrunch.app.getController('SliderController');
    controller.showPersonalStream();

    console.log('asd');
  },

  showFriendProfile: function(button, e, options) {
    qrunch.app.getController('SliderController').showFriendProfile();
  },

  onFollowersTap: function(button, e, options) {
    qrunch.app.getController('SliderController').showFollow();
  },

  onFollowingTap: function(button, e, options) {
    qrunch.app.getController('SliderController').showPersonalStream();
  }

});