/*
 * File: app/view/TopBar.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('qrunch.view.TopBar', {
  extend: 'Ext.Toolbar',
  alias: 'widget.TopBar',

  config: {
    baseCls: 'top-bar',
    docked: 'top',
    id: 'topbar',
    items: [
      {
        xtype: 'button',
        baseCls: 'top-bar-left-btn',
        itemId: 'slide-button',
        pressedCls: 'highlight-pressed'
      },
      {
        xtype: 'spacer'
      },
      {
        xtype: 'button',
        baseCls: 'search-btn',
        id: 'search-btn',
        itemId: 'mybutton13',
        pressedCls: 'highlight-pressed'
      }
    ],
    listeners: [
      {
        fn: 'fillImages',
        event: 'tap',
        delegate: '#search-btn'
      }
    ]
  },

  fillImages: function(button, e, options) {
    var page = Ext.getCmp('friend-profile');

    Ext.data.JsonP.request({
      url: 'http://pipes.yahoo.com/pipes/pipe.run?_id=6820d4a57377bbe8db29796694b2125f&_render=json&textinput1=milan&_render=jsonp',
      callbackKey: '_callback',

      success: function(response){
        var result = response;

        var total = result.count;

        var index = 1;
        var carousel = Ext.create('qrunch.view.InfCarousel');
        console.log(result);
        while (index < total){
          if (index%10==0){
            page.add(carousel);
            carousel = Ext.create('qrunch.view.InfCarousel');
          }

          if (result.value.items[index]["media:content"]!=null){
            var imgurl = result.value.items[index]["media:content"]["url"];
            var html = "<img src='" + imgurl + "' style='width: 100%; height: 100%'/>";
            carousel.add({xtype: 'panel', html: html});
          }      

          index = index+1;
        }
      }
    });

  }

});