/*
 * File: app/controller/SliderController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('qrunch.controller.SliderController', {
  extend: 'Ext.app.Controller',

  config: {
    refs: {
      contentView: '#content-view',
      topbar: '#topbar',
      sliderView: '#slider-view'
    },

    control: {
      "button#content-selection": {
        tap: 'showContentSelection'
      },
      "button#interests": {
        tap: 'showInterests'
      },
      "button#friend-profile": {
        tap: 'showFriendProfile'
      },
      "button#slide-button": {
        tap: 'toggleSlider'
      },
      "button#follow": {
        tap: 'showFollow'
      },
      "panel#mypanel15": {
        tap: 'showPersonalStream'
      }
    }
  },

  showContentSelection: function(button, e, options) {
    this.getContentView().setActiveItem(0);

    this.getTopbar().show();

    this.deactivateSlider();
  },

  showInterests: function(button, e, options) {
    this.deactivateSlider();
    this.getContentView().setActiveItem(3);
  },

  showFriendProfile: function(button, e, options) {
    this.deactivateSlider();
    this.getContentView().setActiveItem(2);
  },

  toggleSlider: function(button, e, options) {
    if (this.getSliderView().isHidden()) {
      this.getSliderView().show();   
    }

    var main = Ext.get('main-view');

    if (main.hasCls('out')) {
      main.removeCls('out');
      main.addCls('in'); 
    } else {
      main.removeCls('in');
      main.addCls('out');
    }

  },

  showFollow: function(button, e, options) {
    this.deactivateSlider();
    this.getContentView().setActiveItem(4);
  },

  showPersonalStream: function(panel) {
    this.deactivateSlider();
    this.getContentView().setActiveItem(1);
  },

  activateSlider: function() {
    this.getSliderView().show();

    var main = Ext.get('main-view');
    main.removeCls('in');
    main.addCls('out');

  },

  deactivateSlider: function() {
    this.getSliderView().hide();

    var main = Ext.get('main-view');
    main.removeCls('out');
    main.addCls('in'); 

  }

});