/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('qrunch.view.MainView', {
  extend: 'Ext.Container',
  alias: 'widget.MainView',

  config: {
    height: '100%',
    id: 'main-view',
    left: 0,
    width: '100%',
    zIndex: 5,
    layout: {
      type: 'card'
    },
    cls: [
      'slide'
    ]
  }

});