/*
 * File: app/view/FriendProfile.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('qrunch.view.FriendProfile', {
  extend: 'Ext.Container',
  alias: 'widget.FriendProfile',

  config: {
    id: 'friend-profile',
    layout: {
      type: 'vbox'
    },
    cls: [
      'bg'
    ],
    scrollable: {
      direction: 'vertical',
      directionLock: true,
      
    },
    items: [
      {
        xtype: 'panel',
        height: '155px',
        html: '<div style="height: 155px; background-image: url(resources/images/bashir.png);"><div style="position: absolute; bottom: 0; background-color: rgba(0,0,0,0.4); width: 100%; color: white; font-size: 20px; font-weight: bold; padding: 5px 10px;">Bashir Osman</div></div>',
        style: 'margin: 4%;'
      },
      {
        xtype: 'panel',
        height: '50px',
        html: '<div style="text-align: center; color: white; font-weight: bold;">Statistics Placeholder</div>',
        styleHtmlContent: true
      },
      {
        xtype: 'label',
        baseCls: 'centered-lbl',
        html: 'Stream'
      }
    ]
  }

});