/*
 * File: app/view/RootView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('qrunch.view.RootView', {
  extend: 'Ext.Container',
  alias: 'widget.RootView',

  requires: [
    'qrunch.view.LoginView',
    'qrunch.view.SlidingView',
    'qrunch.view.SliderView',
    'qrunch.view.MainView',
    'qrunch.view.TopBar',
    'qrunch.view.ContentView',
    'qrunch.view.ContentSelection',
    'qrunch.view.PersonalStream',
    'qrunch.view.FriendProfile',
    'qrunch.view.Interests',
    'qrunch.view.Follow',
    'qrunch.view.RegistrationView'
  ],

  config: {
    id: 'root-view',
    layout: {
      type: 'card'
    },
    cls: [
      'bg'
    ],
    items: [
      {
        xtype: 'LoginView'
      },
      {
        xtype: 'SlidingView',
        items: [
          {
            xtype: 'SliderView'
          },
          {
            xtype: 'MainView',
            items: [
              {
                xtype: 'TopBar'
              },
              {
                xtype: 'ContentView',
                items: [
                  {
                    xtype: 'ContentSelection'
                  },
                  {
                    xtype: 'PersonalStream'
                  },
                  {
                    xtype: 'FriendProfile'
                  },
                  {
                    xtype: 'Interests'
                  },
                  {
                    xtype: 'Follow'
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        xtype: 'registrationview'
      }
    ]
  }

});