/*
 * File: app/view/Follow.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('qrunch.view.Follow', {
  extend: 'Ext.Container',
  alias: 'widget.Follow',

  config: {
    id: 'follow',
    layout: {
      type: 'card'
    },
    scrollable: {
      direction: 'horizontal',
      directionLock: true,
      momentumEasing: {
        momentum: {
          acceleration: 30,
          friction: 0.5
        },
        bounce: {
          acceleration: 0.0001,
          springTension: 0.9999,
          
        },
        minVelocity: 5
      },
      outOfBoundRestrictFactor: 0
    },
    items: [
      {
        xtype: 'segmentedbutton',
        docked: 'top',
        height: '45px',
        pressedCls: 'follow-btn-pressed',
        items: [
          {
            xtype: 'button',
            pressed: true,
            baseCls: '',
            cls: 'follow-btn',
            width: '50%',
            pressedCls: '',
            text: 'FOLLOWING'
          },
          {
            xtype: 'button',
            baseCls: '',
            cls: 'follow-btn',
            width: '50%',
            pressedCls: '',
            text: 'FOLLOWERS'
          }
        ]
      },
      {
        xtype: 'list',
        itemCls: 'follow-list',
        itemTpl: [
          '<div class="list-item-content">',
          '  <div class="avatar">',
          '    <img src="{avatar}" class="avatar">',
          '  </div>',
          '  <div class="user-info">',
          '    <div style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-size: 18px; font-weight: bold; color: rgb(80,80,80);">{name}</div>',
          '    <div style="font-size: 13px; color: gray;">@{hashtag}</div>',
          '    <div style="font-size: 15px; color: gray;">{fans} followers</div>',
          '  </div>',
          '  <div style="display: inline-block; vertical-align: center; width: 0px; float: right; height: 55px; border-right: solid 1px rgb(200,200,200);">    ',
          '  </div>',
          '</div>'
        ],
        pressedCls: 'x-item',
        selectedCls: 'x-item',
        store: 'Followers',
        itemHeight: 70,
        onItemDisclosure: true
      }
    ]
  }

});